language: erlang
otp_release:
  - 21.0.5
  - 20.3
  - 19.3
# jobs:
#   include:
#     - stage: deploy
#       otp_release: 20.3
#       script: skip
#       deploy:
#         provider: script
#         script: ./hex.sh
#         skip_cleanup: true
#         on:
#           tags: true
#           all_branches: true
script: make clean test
sudo: false
notifications:
  email:
    recipients:
      - zotonic-commits@googlegroups.com
    on_success: change #[always|never|change] # default: change
    on_failure: always #[always|never|change] # default: always
